name: Analyze and build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: dart-lang/setup-dart@v1.7.2
      with:
        sdk: stable
    - run: dart pub global activate jaspr_cli
    - run: dart pub get
    - run: dart run slang
    - run: dart run build_runner build --delete-conflicting-outputs
    - run: dart analyze
    - run: jaspr build
